name       : zynaddsubfx
version    : 3.0.0
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/zynaddsubfx/zynaddsubfx/3.0.0/zynaddsubfx-3.0.0.tar.bz2 : 94593db88402dedd2f451720b81dd1caea1217a954349bbf254620c12904c45c
license    : GPL-2.0
component  : multimedia.audio
summary    : a feature heavy realtime software synthesizer for Linux
description: |
    a feature heavy realtime software synthesizer for Linux
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(liblo)
    - pkgconfig(mxml)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(xft)
    - pkgconfig(xpm)
    - fltk-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rm -f $installdir/usr/share/applications/zynaddsubfx-jack.desktop
