name       : zynaddsubfx
version    : 3.0.6
release    : 11
source     :
    - git|https://github.com/zynaddsubfx/zynaddsubfx.git : 3.0.6
homepage   : https://zynaddsubfx.sourceforge.io/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fully featured musical software synthesizer
description: |
    ZynAddSubFX is a fully featured musical software synthesizer. ZynAddSubFX exposes a wide array of synthesis parameters to make it flexible tool for sound design and a fun experience for playing instruments.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(mxml)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
    - pkgconfig(xpm)
    - fltk-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/share/applications/zynaddsubfx-oss.desktop
