name       : zynaddsubfx
version    : 3.0.5
release    : 5
source     :
    - git|https://github.com/zynaddsubfx/zynaddsubfx.git : 3.0.5
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fully featured musical software synthesizer
description: |
    A feature heavy realtime software synthesizer for Linux.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(mxml)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(xft)
    - pkgconfig(xpm)
    - fltk-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/share/applications/zynaddsubfx-oss.desktop
